/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DuAnDAO.NhanVienDAO;
import DuAnDAO.ThanNhanDAO;
import Entity.NhanVien;
import Entity.ThanNhan;
import Helper.DialogHelper;
import Helper.ShareHelper;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Admin
 */
public class DangNhap extends javax.swing.JDialog {

    /**
     * Creates new form DangNhap
     */
    public DangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnQuenMK = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnQrCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        txtMaNV.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtMaNV.setText("ThienVD");
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 230, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mời bạn đăng nhập để truy cập ứng dụng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, -1));

        txtMatKhau.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtMatKhau.setText("123");
        txtMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, 30));

        btnDangNhap.setBackground(new java.awt.Color(51, 0, 153));
        btnDangNhap.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.setOpaque(true);
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 170, 30));

        btnQuenMK.setBackground(new java.awt.Color(255, 255, 255));
        btnQuenMK.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnQuenMK.setForeground(new java.awt.Color(255, 0, 0));
        btnQuenMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuenMK.setText("Quên mật khẩu");
        btnQuenMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuenMK.setOpaque(true);
        btnQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuenMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuenMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuenMKMouseExited(evt);
            }
        });
        jPanel1.add(btnQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, -1));

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/icons8_delete_24px_1.png"))); // NOI18N
        btnThoat.setContentAreaFilled(false);
        btnThoat.setOpaque(true);
        btnThoat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/icons8_delete_24px.png"))); // NOI18N
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThoatMouseExited(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setText("Tên đăng nhập");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnAI.setBackground(new java.awt.Color(255, 255, 255));
        btnAI.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnAI.setForeground(new java.awt.Color(102, 102, 255));
        btnAI.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAI.setText(" Đăng nhập bằng khuôn mặt");
        btnAI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAI.setOpaque(true);
        btnAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAIMouseExited(evt);
            }
        });
        jPanel1.add(btnAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Xin chào ! Chúng tôi là Euphoria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/5e9ccdf3d3886a5784f7c38d_5e84ba890813bd37c3c60fdf_Medica20Template20-201 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 380, -1));

        btnQrCode.setBackground(new java.awt.Color(255, 255, 255));
        btnQrCode.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnQrCode.setForeground(new java.awt.Color(102, 102, 255));
        btnQrCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQrCode.setText(" Đăng nhập bằng QR Code");
        btnQrCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQrCode.setOpaque(true);
        btnQrCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQrCodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQrCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQrCodeMouseExited(evt);
            }
        });
        jPanel1.add(btnQrCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        btnDangNhap.setForeground(new Color(231, 255, 1));
        btnDangNhap.setBackground(new Color(247, 149, 157));
    }//GEN-LAST:event_btnDangNhapMouseEntered

    private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
        btnDangNhap.setForeground(new Color(255, 255, 255));
        btnDangNhap.setBackground(new Color(51,0,153));
    }//GEN-LAST:event_btnDangNhapMouseExited

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnQuenMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuenMKMouseEntered
        btnQuenMK.setForeground(new Color(247, 118, 102));
        btnQuenMK.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 14));
    }//GEN-LAST:event_btnQuenMKMouseEntered

    private void btnQuenMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuenMKMouseExited
        btnQuenMK.setForeground(new Color(255, 51, 51));
        btnQuenMK.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    }//GEN-LAST:event_btnQuenMKMouseExited

    private void btnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseEntered

    }//GEN-LAST:event_btnThoatMouseEntered

    private void btnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatMouseExited

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuenMKMouseClicked
        // TODO add your handling code here:
        quenMatKhau();
    }//GEN-LAST:event_btnQuenMKMouseClicked

    private void btnAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAIMouseClicked
        AI();
    }//GEN-LAST:event_btnAIMouseClicked

    private void btnAIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAIMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAIMouseEntered

    private void btnAIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAIMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAIMouseExited

    private void btnQrCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQrCodeMouseClicked
        // TODO add your handling code here:
        QR();
    }//GEN-LAST:event_btnQrCodeMouseClicked

    private void btnQrCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQrCodeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQrCodeMouseEntered

    private void btnQrCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQrCodeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQrCodeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap dialog = new DangNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    NhanVienDAO dao = new NhanVienDAO();
    ThanNhanDAO tndao = new ThanNhanDAO();
     void login() {
        String manv = txtMaNV.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        try {
            NhanVien nhanVien = dao.selectByID(manv);
            ThanNhan thanhan = tndao.selectByID(manv);
            if (nhanVien != null) {
                String matKhau2 = nhanVien.getMatKhau();
                if (matKhau.equals(matKhau2)) {
                    ShareHelper.user = nhanVien;
                    System.out.println(ShareHelper.user.getMaNV());
                    DialogHelper.alert(this, "Đăng nhập thành công!");
                    this.dispose();
                } else {
                    DialogHelper.alert(this, "Sai mật khẩu!");
                }
            }else if (thanhan != null) {
                String matKhau2 = thanhan.getPass();
                if (matKhau.equals(matKhau2)) {
                    ShareHelper.nguoidung = thanhan;
                    System.out.println(ShareHelper.nguoidung.getMatn());
                    DialogHelper.alert(this, "Đăng nhập thành công thân nhân");
                    this.dispose();
                } else {
                    DialogHelper.alert(this, "Sai mật khẩu!");
                }
            } 
            else {
                DialogHelper.alert(this, "Sai tên đăng nhập!");
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    void exit() {
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);
        }
    }

    public void quenMatKhau() {
        this.dispose();
        new QuenMatKhau(null, true).setVisible(true);
    }
    public void AI() {
        this.dispose();
        new KhuonMatJDialog(null, true).setVisible(true);
    }
    public void QR() {
        this.dispose();
        new QrCodeJDialog(null, true).setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAI;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel btnQrCode;
    private javax.swing.JLabel btnQuenMK;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
