/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DuAnDAO.*;
import Entity.*;
import Helper.CheckHelper;
import Helper.DateHelper;
import Helper.DialogHelper;
import Helper.FormatHepler;
import Helper.ShareHelper;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class HoaDonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonJPanel
     */
    public HoaDonJPanel() {
        initComponents();

        this.init();
        if (ShareHelper.isLogin1()) {
            btnThemHD.setVisible(false);
            btnNewHD.setVisible(false);
        } else {
            btnThemHD.setVisible(true);
            btnNewHD.setVisible(true);
        }
    }
    PhongDAO phongdao = new PhongDAO();

    public String thongtinbill() {
        String thongtin = "===========================================================================================" + "\n"
                + "\tTrại cai nghiện Euphoria" + "\n"
                + "Số điện thoại : 0966641029" + "\n"
                + "245 Bình Quới, Phường 28, Bình Thạnh, Thành phố Hồ Chí Minh" + "\n"
                + "===========================================================================================" + "\n"
                + "Họ tên bệnh nhân : " + lblTenBN.getText() + "\n"
                + "Mã phòng : " + lblMaPhong2.getText() + "\n"
                + "Giá phòng 1 tháng : " + phongdao.findById(lblMaPhong2.getText()).getGia() + "\n"
                + "Số tháng thanh toán : " + lblSoThangTT.getText() + "\n"
                + "Ngày bắt đầu : " + lblNgayBatDau2.getText() + "\n"
                + "Ngày kết thúc : " + lblNgayKetThuc2.getText() + "\n"
                + "===========================================================================================" + "\n";
        return thongtin;
    }

    public String dichvubill() {
        HoaDon hd = this.getForm();
        BenhNhan bn = benhNhanDAO.selectByID(hd.getMaBN());
        List<DichVuCT> listDV = dvctDAO.selectByMaBNAndNgayDK(bn.getMaBN(), hd.getNgayBDTT(), hd.getNgayKTTT());
        String name = "";
        for (DichVuCT dichVuCT : listDV) {

            DichVu dv = dichVuDAO.selectByID(dichVuCT.getMaDV());
            name += "Dịch vụ : " + dv.getTenDV() + "\t"
                    + "Giá : " + String.valueOf(dv.getGia()) + "\t"
                    + "Ngày đăng ký : " + DateHelper.toString(dichVuCT.getNgayDK()) + "\n";

        }

        return name;
    }

    public void bill() {
        txtbill.setText(
                thongtinbill() + dichvubill()
                + "Giá phòng : " + lblGiaPhong.getText() + "\n"
                + "===========================================================================================" + "\n"
                + "Tổng tiền : " + lblTongTien2.getText() + "\n"
                + "===========================================================================================" + "\n"
                + "Tiền khách đưa : " + txtTienKhachDua.getText() + "\n"
                + "Tiền thừa : " + lblTienThua.getText() + "\n"
                + "===========================================================================================" + "\n"
                + "Cảm ơn bạn đã tin tưởng chúng tôi " + "\n"
                + "Chúc bạn 1 ngày tốt lành "
        );

    }

    public void billsaukhithanhtoan() {
        txtbill.setText(
                thongtinbill() + dichvubill()
                + "Giá phòng : " + lblGiaPhong.getText() + "\n"
                + "===========================================================================================" + "\n"
                + "Tổng tiền : " + lblTongTien2.getText() + "\n"
                + "===========================================================================================" + "\n"
                + "\tCảm ơn bạn đã tin tưởng chúng tôi " + "\n"
                + "\tChúc bạn 1 ngày tốt lành "
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnUndo = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        btnNewHD = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        cboTenBN = new javax.swing.JComboBox();
        btnThemHD = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        txtSoThangTT = new javax.swing.JTextField();
        lblMaPhong = new javax.swing.JLabel();
        txtNgayThanhToan = new com.toedter.calendar.JDateChooser();
        lblSoThangCanTT = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lblNgayBatDau = new javax.swing.JLabel();
        lblNgayKetThuc = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnXemChiTiet = new javax.swing.JButton();
        lblMenuRedo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new rojeru_san.complementos.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lblTenBN = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        lblNgayBatDau2 = new javax.swing.JLabel();
        lblNgayKetThuc2 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        lblTongTien2 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        lblMaPhong2 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        lblGiaPhong = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblSoThangTT = new javax.swing.JLabel();
        btnExcel1 = new javax.swing.JButton();
        btnThemHD1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDichVuCT = new rojeru_san.complementos.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();

        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnUndo);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 875));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 133, 253));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("QUẢN LÝ HÓA ĐƠN");

        jLabel54.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 102, 102));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/ngayThanhToan.png"))); // NOI18N
        jLabel54.setText("Ngày thanh toán");

        btnNewHD.setBackground(new java.awt.Color(50, 133, 253));
        btnNewHD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNewHD.setForeground(new java.awt.Color(255, 255, 255));
        btnNewHD.setText("MỚI");
        btnNewHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNewHD.setContentAreaFilled(false);
        btnNewHD.setOpaque(true);
        btnNewHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewHDMouseExited(evt);
            }
        });
        btnNewHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewHDActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 102, 102));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/maPhong.png"))); // NOI18N
        jLabel53.setText("Mã phòng");

        jLabel55.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 102, 102));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/soThangCanThanhToan.png"))); // NOI18N
        jLabel55.setText("Số tháng cần TT");

        jLabel56.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 102, 102));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/soThangThanhToan.png"))); // NOI18N
        jLabel56.setText("Số tháng TT");

        cboTenBN.setEditable(true);
        cboTenBN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboTenBN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        cboTenBN.setFocusable(false);
        cboTenBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenBNActionPerformed(evt);
            }
        });

        btnThemHD.setBackground(new java.awt.Color(50, 133, 253));
        btnThemHD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThemHD.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHD.setText("THANH TOÁN");
        btnThemHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemHD.setContentAreaFilled(false);
        btnThemHD.setOpaque(true);
        btnThemHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemHDMouseExited(evt);
            }
        });
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tenBN.png"))); // NOI18N
        jLabel49.setText("Tên bệnh nhân");

        txtSoThangTT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtSoThangTT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        txtSoThangTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoThangTTKeyReleased(evt);
            }
        });

        lblMaPhong.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        txtNgayThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayThanhToan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        txtNgayThanhToan.setDateFormatString("dd/MM/yyyy");
        txtNgayThanhToan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        lblSoThangCanTT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel59.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(102, 102, 102));
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/ngayBatDauThanhToan.png"))); // NOI18N
        jLabel59.setText("Ngày bắt đầu");

        lblNgayBatDau.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        lblNgayKetThuc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel62.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(102, 102, 102));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/ngayBatDauThanhToan.png"))); // NOI18N
        jLabel62.setText("Ngày bắt đầu");

        jLabel63.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(102, 102, 102));
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tongTien.png"))); // NOI18N
        jLabel63.setText("Tổng tiền");

        lblTongTien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnXemChiTiet.setBackground(new java.awt.Color(50, 133, 253));
        btnXemChiTiet.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXemChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXemChiTiet.setContentAreaFilled(false);
        btnXemChiTiet.setOpaque(true);
        btnXemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXemChiTietMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXemChiTietMouseExited(evt);
            }
        });
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        lblMenuRedo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblMenuRedo.setText("...");
        lblMenuRedo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuRedoMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/gia.png"))); // NOI18N
        jLabel1.setText("Tiền khách đưa");

        txtTienKhachDua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTienKhachDua.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/gia.png"))); // NOI18N
        jLabel2.setText("Tiền thừa");

        lblTienThua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên bệnh nhân", "Ngày thanh toán", "Số tháng thanh toán", "Ngày bắt đầu", "Ngày kết thúc", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setColorBackgoundHead(new java.awt.Color(51, 133, 253));
        tblHoaDon.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblHoaDon.setColorBordeHead(new java.awt.Color(51, 133, 253));
        tblHoaDon.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblHoaDon.setColorFilasForeground1(new java.awt.Color(51, 133, 253));
        tblHoaDon.setColorFilasForeground2(new java.awt.Color(51, 133, 253));
        tblHoaDon.setColorSelBackgound(new java.awt.Color(51, 133, 253));
        tblHoaDon.setFuenteFilas(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblHoaDon.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblHoaDon.setFuenteHead(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tblHoaDon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblHoaDon.setRowHeight(25);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel59)
                                            .addComponent(jLabel63)
                                            .addComponent(jLabel2))
                                        .addGap(58, 58, 58))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel49)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel53))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSoThangTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblSoThangCanTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMaPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboTenBN, javax.swing.GroupLayout.Alignment.LEADING, 0, 372, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblTienThua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                .addGap(28, 28, 28)
                                                .addComponent(lblNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGap(1018, 1018, 1018))
                    .addComponent(lblMenuRedo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(613, 613, 613)
                .addComponent(btnNewHD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel54)
                        .addComponent(jLabel55)
                        .addComponent(jLabel56)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(1078, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(611, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblMenuRedo)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(cboTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel53)
                    .addComponent(lblMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblSoThangCanTT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtSoThangTT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel59)
                        .addComponent(lblNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel62)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnNewHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(265, 265, 265)
                    .addComponent(jLabel54)
                    .addGap(25, 25, 25)
                    .addComponent(jLabel55)
                    .addGap(25, 25, 25)
                    .addComponent(jLabel56)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(100, 100, 100)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel58.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 102, 102));
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/maPhong.png"))); // NOI18N
        jLabel58.setText("Mã phòng");

        jLabel61.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(102, 102, 102));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/soThangCanThanhToan.png"))); // NOI18N
        jLabel61.setText("Số tháng TT");

        jLabel50.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tenBN.png"))); // NOI18N
        jLabel50.setText("Tên bệnh nhân");

        lblTenBN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTenBN.setText("NULL");

        jLabel64.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(102, 102, 102));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/ngayBatDauThanhToan.png"))); // NOI18N
        jLabel64.setText("Ngày bắt đầu");

        lblNgayBatDau2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNgayBatDau2.setText("NULL");

        lblNgayKetThuc2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNgayKetThuc2.setText("NULL");

        jLabel65.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_binary_file_35px.png"))); // NOI18N
        jLabel65.setText("Ngày bắt đầu");

        jLabel66.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(102, 102, 102));
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tongTien.png"))); // NOI18N
        jLabel66.setText("Tổng tiền");

        lblTongTien2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTongTien2.setText("0.0");

        btnQuayLai.setBackground(new java.awt.Color(50, 133, 253));
        btnQuayLai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        btnQuayLai.setText("Quay lại hóa đơn");
        btnQuayLai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnQuayLai.setContentAreaFilled(false);
        btnQuayLai.setOpaque(true);
        btnQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuayLaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuayLaiMouseExited(evt);
            }
        });
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        lblMaPhong2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMaPhong2.setText("R000");

        jLabel67.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_binary_file_35px.png"))); // NOI18N
        jLabel67.setText("Giá phòng");

        lblGiaPhong.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGiaPhong.setText("0.0");

        lblTitle1.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(51, 133, 253));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("HÓA ĐƠN CHI TIẾT");

        lblSoThangTT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSoThangTT.setText("0");

        btnExcel1.setBackground(new java.awt.Color(50, 133, 253));
        btnExcel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExcel1.setForeground(new java.awt.Color(255, 255, 255));
        btnExcel1.setText("Xuất hóa đơn");
        btnExcel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExcel1.setContentAreaFilled(false);
        btnExcel1.setOpaque(true);
        btnExcel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcel1MouseExited(evt);
            }
        });
        btnExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel1ActionPerformed(evt);
            }
        });

        btnThemHD1.setBackground(new java.awt.Color(50, 133, 253));
        btnThemHD1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThemHD1.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHD1.setText("THANH TOÁN");
        btnThemHD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemHD1.setContentAreaFilled(false);
        btnThemHD1.setOpaque(true);
        btnThemHD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemHD1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemHD1MouseExited(evt);
            }
        });
        btnThemHD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHD1ActionPerformed(evt);
            }
        });

        tblDichVuCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Ngày đăng ký", "Tiền dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVuCT.setColorBackgoundHead(new java.awt.Color(51, 133, 253));
        tblDichVuCT.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblDichVuCT.setColorBordeHead(new java.awt.Color(51, 133, 253));
        tblDichVuCT.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblDichVuCT.setColorFilasForeground1(new java.awt.Color(51, 133, 253));
        tblDichVuCT.setColorFilasForeground2(new java.awt.Color(51, 133, 253));
        tblDichVuCT.setColorSelBackgound(new java.awt.Color(51, 133, 253));
        tblDichVuCT.setFuenteFilas(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblDichVuCT.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblDichVuCT.setFuenteHead(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tblDichVuCT.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDichVuCT.setRowHeight(25);
        tblDichVuCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDichVuCT);

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane3.setViewportView(txtbill);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(18, 18, 18)
                                .addComponent(lblTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel64)
                                        .addComponent(jLabel66))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNgayBatDau2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTongTien2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel61)
                                        .addComponent(jLabel58))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(lblMaPhong2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(76, 76, 76)
                                            .addComponent(jLabel67)
                                            .addGap(37, 37, 37)
                                            .addComponent(lblGiaPhong))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel65)
                                            .addGap(30, 30, 30)
                                            .addComponent(lblNgayKetThuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblSoThangTT, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnExcel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnThemHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1036, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(629, 629, 629)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblTitle1)
                .addGap(100, 100, 100)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(lblTenBN))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaPhong2)
                    .addComponent(jLabel67)
                    .addComponent(lblGiaPhong)
                    .addComponent(jLabel58))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(lblSoThangTT))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(lblNgayBatDau2)
                    .addComponent(jLabel65)
                    .addComponent(lblNgayKetThuc2))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel66)
                            .addComponent(lblTongTien2))
                        .addGap(42, 42, 42)
                        .addComponent(btnThemHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(764, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(115, 115, 115)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(502, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1657, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        if (txtSoThangTT.getText().isEmpty()) {
            DialogHelper.alert(this, "Bạn chưa nhập số tháng thanh toán");
        } else if (isInvalidSoTTT()) {
            txtbill.setText("");
            this.viewDichVuCT();
            this.fillTableDVCT();
            this.setFormDVCT();
        }
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void cboTenBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenBNActionPerformed
        this.SelectBenhNhan();
    }//GEN-LAST:event_cboTenBNActionPerformed

    private void btnNewHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewHDActionPerformed
        cboTenBN.setSelectedIndex(0);
        btnXemChiTiet.setEnabled(false);
        this.clearForm();
        this.row = -2;
        this.updateStatus();
    }//GEN-LAST:event_btnNewHDActionPerformed

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        this.setFormDVCT();
        exportpdf();
        this.insert();

    }//GEN-LAST:event_btnThemHDActionPerformed

    private void txtSoThangTTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoThangTTKeyReleased
        if (isInvalidSoTTT()) {
            if (Integer.parseInt(txtSoThangTT.getText()) <= Integer.parseInt(lblSoThangCanTT.getText())) {
                this.fillNgayBD();
                this.fillNgayKT();
                this.fillTongTien();

            } else {
                DialogHelper.alert(this, "Số tháng thanh toán không được lớn hơn số tháng cần thanh toán");
                txtSoThangTT.setText("");

            }

        }
    }//GEN-LAST:event_txtSoThangTTKeyReleased

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        txtbill.setText("");
        this.viewDichVuCT();

    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        this.undo();
        this.fillThangCanTT();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void lblMenuRedoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuRedoMouseClicked
        this.showMenuRedo();
    }//GEN-LAST:event_lblMenuRedoMouseClicked

    private void btnExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel1ActionPerformed
        // TODO add your handling code here:
        try {
            txtbill.getText();
            txtbill.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi lưu file");
        }
    }//GEN-LAST:event_btnExcel1ActionPerformed

    private void btnThemHD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHD1ActionPerformed
        this.insert();
        this.viewDichVuCT();
    }//GEN-LAST:event_btnThemHD1ActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        this.fillTienThua();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        if (evt.getClickCount() == 2) {
            isLoad = false;
            this.row = tblHoaDon.getSelectedRow();
            this.edit();
            isLoad = true;
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnXemChiTietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemChiTietMouseEntered
        btnXemChiTiet.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnXemChiTietMouseEntered

    private void btnNewHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewHDMouseEntered
        btnNewHD.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnNewHDMouseEntered

    private void btnThemHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHDMouseEntered
        btnThemHD.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnThemHDMouseEntered

    private void btnXemChiTietMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemChiTietMouseExited
        btnXemChiTiet.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnXemChiTietMouseExited

    private void btnNewHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewHDMouseExited
        btnNewHD.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnNewHDMouseExited

    private void btnThemHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHDMouseExited
        btnThemHD.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnThemHDMouseExited

    private void tblDichVuCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuCTMouseClicked

    }//GEN-LAST:event_tblDichVuCTMouseClicked

    private void btnThemHD1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHD1MouseEntered
        btnThemHD1.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnThemHD1MouseEntered

    private void btnThemHD1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHD1MouseExited
        btnThemHD1.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnThemHD1MouseExited

    private void btnExcel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel1MouseEntered
        btnExcel1.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnExcel1MouseEntered

    private void btnExcel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel1MouseExited
        btnExcel1.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnExcel1MouseExited

    private void btnQuayLaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuayLaiMouseEntered
        btnQuayLai.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnQuayLaiMouseEntered

    private void btnQuayLaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuayLaiMouseExited
        btnQuayLai.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnQuayLaiMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel1;
    private javax.swing.JButton btnNewHD;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnThemHD1;
    private javax.swing.JMenuItem btnUndo;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JComboBox cboTenBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblGiaPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblMaPhong2;
    private javax.swing.JLabel lblMenuRedo;
    private javax.swing.JLabel lblNgayBatDau;
    private javax.swing.JLabel lblNgayBatDau2;
    private javax.swing.JLabel lblNgayKetThuc;
    private javax.swing.JLabel lblNgayKetThuc2;
    private javax.swing.JLabel lblSoThangCanTT;
    private javax.swing.JLabel lblSoThangTT;
    private javax.swing.JLabel lblTenBN;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien2;
    private rojeru_san.complementos.RSTableMetro tblDichVuCT;
    private rojeru_san.complementos.RSTableMetro tblHoaDon;
    private com.toedter.calendar.JDateChooser txtNgayThanhToan;
    private javax.swing.JTextField txtSoThangTT;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables

    List<HoaDon> listUndo = new ArrayList<>();
    List<Integer> listBrowser = new ArrayList<>();
    int index = -1;

    boolean isLoad = false;
    int row = -1;
    HoaDonDAO hoaDonDAO = new HoaDonDAO();
    BenhNhanDAO benhNhanDAO = new BenhNhanDAO();
    DichVuDAO dichVuDAO = new DichVuDAO();
    PhongDAO phongDAO = new PhongDAO();
    DichVuCTDAO dvctDAO = new DichVuCTDAO();

    public void init() {
        this.fillComboxTenBN();
        fillTable();
        txtSoThangTT.setEnabled(false);
        txtTienKhachDua.setEnabled(false);
        txtNgayThanhToan.setEnabled(false);
        btnXemChiTiet.setEnabled(false);
        btnThemHD.setEnabled(false);
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        BenhNhan benhNhan = (BenhNhan) cboTenBN.getSelectedItem();
        List<HoaDon> list;
        if (ShareHelper.isLogin()) {
            if (benhNhan.getMaBN() != -1) {
                try {
                    list = hoaDonDAO.selectByMaBN(benhNhan.getMaBN());
                    for (HoaDon hd : list) {
                        if (hd.getMaBN() >= 1) {
                            Object[] row = {
                                hd.getMaHD(),
                                benhNhanDAO.selectByID(hd.getMaBN()).getHoTen(),
                                DateHelper.toString(hd.getNgayThanhToan()),
                                hd.getThoiGian(),
                                DateHelper.toString(hd.getNgayBDTT()),
                                DateHelper.toString(hd.getNgayKTTT()),
                                FormatHepler.formatMoney(hd.getTongTien())
                            };
                            model.addRow(row);
                        }
                    }
                } catch (Exception e) {
                    DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
                    System.out.println(e);
                }
            } else {
                try {
                    list = hoaDonDAO.selectAll();
                    for (HoaDon hd : list) {
                        if (hd.getMaBN() >= 1) {
                            Object[] row = {
                                hd.getMaHD(),
                                benhNhanDAO.selectByID(hd.getMaBN()).getHoTen(),
                                DateHelper.toString(hd.getNgayThanhToan()),
                                hd.getThoiGian(),
                                DateHelper.toString(hd.getNgayBDTT()),
                                DateHelper.toString(hd.getNgayKTTT()),
                                FormatHepler.formatMoney(hd.getTongTien())
                            };
                            model.addRow(row);
                        }
                    }
                } catch (Exception e) {
                    DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
                    System.out.println(e);
                }
            }
        } else if (ShareHelper.isLogin1()) {
            try {
                list = hoaDonDAO.selectByMaBN(ShareHelper.nguoidung.getMabn());
                for (HoaDon hd : list) {
                    Object[] row = {
                        hd.getMaHD(),
                        benhNhanDAO.selectByID(hd.getMaBN()).getHoTen(),
                        DateHelper.toString(hd.getNgayThanhToan()),
                        hd.getThoiGian(),
                        DateHelper.toString(hd.getNgayBDTT()),
                        DateHelper.toString(hd.getNgayKTTT()),
                        FormatHepler.formatMoney(hd.getTongTien())
                    };
                    model.addRow(row);
                }
            } catch (Exception e) {
                DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
                System.out.println(e);
            }
        }

    }

    public void fillNgayBD() {
        if (tblHoaDon.getRowCount() != 0) {
            if (!txtSoThangTT.getText().isEmpty()) {
                String ngayBD = (String) tblHoaDon.getValueAt(tblHoaDon.getRowCount() - 1, 5);
                lblNgayBatDau.setText(ngayBD);
            }
        } else {
            BenhNhan bn = (BenhNhan) cboTenBN.getSelectedItem();
            lblNgayBatDau.setText(DateHelper.toString(bn.getNgayVT()));
        }
    }

    public void fillNgayKT() {
        if (!txtSoThangTT.getText().isEmpty()) {
            Date ngayBT = DateHelper.toDate(lblNgayBatDau.getText(), "dd/MM/yyyy");
            Date ngayKT = DateHelper.addMonths(ngayBT, Integer.parseInt(txtSoThangTT.getText()));
            lblNgayKetThuc.setText(DateHelper.toString(ngayKT));
        }
    }

    public void fillComboxTenBN() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenBN.getModel();
        model.removeAllElements();
        if (ShareHelper.isLogin()) {
            List<BenhNhan> list = benhNhanDAO.selectAll();
            BenhNhan benhNhan = new BenhNhan();
            benhNhan.setHoTen("Tất cả");
            benhNhan.setMaBN(-1);
            model.addElement(benhNhan);
            for (BenhNhan bn : list) {
                model.addElement(bn);
            }
            isLoad = true;
//            fillTable();
//            fillLblMaPhong();
//            fillThangCanTT();
        } else {
            List<BenhNhan> list = benhNhanDAO.findlistById(ShareHelper.nguoidung.getMabn());
            for (BenhNhan bn : list) {
                model.addElement(bn);
            }
            fillTable();
            fillLblMaPhong();
            fillThangCanTT();
        }

    }

    public void fillLblMaPhong() {
        BenhNhan benhNhan = (BenhNhan) cboTenBN.getSelectedItem();
        lblMaPhong.setText(benhNhanDAO.selectByID(benhNhan.getMaBN()).getMaPhong());
    }

    public void fillThangCanTT() {

        BenhNhan benhNhan = (BenhNhan) cboTenBN.getSelectedItem();
        List<HoaDon> listHoaDon = hoaDonDAO.selectByMaBN(benhNhan.getMaBN());

        Date ngayHienTai = new Date();
        Date ngayVoTrai = benhNhan.getNgayVT();
        int soThangO = benhNhan.getThoiGianO();
        int soThangDaTT = 0;
        for (int i = 0; i < listHoaDon.size(); i++) {
            soThangDaTT += listHoaDon.get(i).getThoiGian();
        }
        int soThang = DateHelper.subtrDateToMonth(ngayHienTai, ngayVoTrai);
        int tongSoThang = soThang < soThangO ? soThang : soThangO;
        
        lblSoThangCanTT.setText(String.valueOf(tongSoThang - soThangDaTT));
    }

    public void fillTongTien() {
        if (!txtSoThangTT.getText().isEmpty()) {
            Date ngayBD = DateHelper.toDate(lblNgayBatDau.getText());
            Date ngayKT = DateHelper.toDate(lblNgayKetThuc.getText());
            BenhNhan benhNhan = (BenhNhan) cboTenBN.getSelectedItem();
            Phong phong = phongDAO.findById(benhNhan.getMaPhong());
            List<DichVuCT> listDV = dvctDAO.selectByMaBNAndNgayDK(benhNhan.getMaBN(), ngayBD, ngayKT);

//            double tongTien = 0;
            int soThangTT = Integer.parseInt(txtSoThangTT.getText());

            double tongTien = phong.getGia() * soThangTT;
            for (DichVuCT dichVu : listDV) {
                DichVu dv = dichVuDAO.selectByID(dichVu.getMaDV());
                tongTien += dv.getGia();
            }
            lblTongTien.setText(FormatHepler.formatMoney(tongTien));
        }
    }

    public void clearForm() {
        txtSoThangTT.setText("");
        lblNgayBatDau.setText("");
        lblNgayKetThuc.setText("");
        txtNgayThanhToan.setDate(new Date());
        lblTongTien.setText("");
        txtTienKhachDua.setText("");
        lblTienThua.setText("");
    }

    public void insert() {
        if (validateData()) {
            try {
                HoaDon hd = this.getForm();
                System.out.println(hd.getMaBN());
                hoaDonDAO.insert(hd);
//                Undo:
                index++;
                List<HoaDon> listHd = hoaDonDAO.selectAll();
                listUndo.add(listHd.get(listHd.size() - 1));
                listBrowser.add(1);
//                
                SelectBenhNhan();
                DialogHelper.alert(this, "Thêm hóa đơn thành công");
            } catch (Exception e) {
                DialogHelper.alert(this, "Thêm thất bại");
                System.out.println(e);
            }
        }
    }

    public void delete() {
        if (DialogHelper.confirm(this, "Bạn muốn xóa hóa đơn này ?")) {
            try {
                int maHD = (int) tblHoaDon.getValueAt(row, 0);

                index++;
                HoaDon hd = hoaDonDAO.selectByID(maHD);
                listUndo.add(hd);
                listBrowser.add(3);

                hoaDonDAO.delete(maHD);
                DialogHelper.alert(this, "Xóa thành công");
                row = -1;
                SelectBenhNhan();
            } catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại");
            }
        }
    }

    public void setForm(HoaDon hd) {
        BenhNhan bn = benhNhanDAO.selectByID(hd.getMaBN());

        txtNgayThanhToan.setDate(hd.getNgayThanhToan());
        txtSoThangTT.setText(String.valueOf(hd.getThoiGian()));
        lblTongTien.setText(FormatHepler.formatMoney(hd.getTongTien()));
        lblNgayBatDau.setText(DateHelper.toString(hd.getNgayBDTT()));
        lblNgayKetThuc.setText(DateHelper.toString(hd.getNgayKTTT()));
    }

    public HoaDon getForm() {
        HoaDon hd = new HoaDon();
        BenhNhan bn = (BenhNhan) cboTenBN.getSelectedItem();
        hd.setMaBN(bn.getMaBN());
        if (ShareHelper.isLogin()) {
            hd.setMaNV(ShareHelper.user.getMaNV());
        } else {
            hd.setMaNV(ShareHelper.nguoidung.getMatn());
        }

        hd.setThoiGian(Integer.parseInt(txtSoThangTT.getText()));
        hd.setNgayBDTT(DateHelper.toDate(lblNgayBatDau.getText(), "dd/MM/yyyy"));
        hd.setNgayKTTT(DateHelper.toDate(lblNgayKetThuc.getText(), "dd/MM/yyyy"));
        hd.setNgayThanhToan(txtNgayThanhToan.getDate());
        hd.setTongTien(FormatHepler.formatMoneyToDouble(lblTongTien.getText()));

        return hd;
    }

    public void edit() {
        row = tblHoaDon.getSelectedRow();
        int maHD = (int) tblHoaDon.getValueAt(this.row, 0);
        HoaDon hd = hoaDonDAO.selectByID(maHD);
        BenhNhan bn = benhNhanDAO.selectByID(hd.getMaBN());
        cboTenBN.setSelectedItem(bn);
        fillTable();
        fillLblMaPhong();
        fillThangCanTT();
        this.setForm(hd);
        this.updateStatus();
        btnXemChiTiet.setEnabled(true);
    }

    private boolean validateData() {
        if (txtSoThangTT.getText().isEmpty()) {
            DialogHelper.alert(this, "Bạn chưa nhập số tháng cần thanh toán");
            txtSoThangTT.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    public void updateStatus() {
        boolean edit = (this.row == -1);
        btnThemHD.setEnabled(edit);
        btnThemHD1.setEnabled(edit);
        txtNgayThanhToan.setEnabled(edit);
        txtSoThangTT.setEnabled(edit);
        txtTienKhachDua.setEnabled(edit);
        btnXemChiTiet.setEnabled(edit);
        if (row >= 0) {
            btnXemChiTiet.setEnabled(true);
        }
    }

    public void SelectBenhNhan() {
        if (isLoad) {
            BenhNhan bn = (BenhNhan) cboTenBN.getSelectedItem();
            if (bn.getMaBN() != -1) {
                this.fillLblMaPhong();
                this.fillThangCanTT();
                this.row = cboTenBN.getSelectedIndex();
                txtSoThangTT.setEnabled(true);
                txtTienKhachDua.setEnabled(true);
                txtNgayThanhToan.setEnabled(true);
                btnXemChiTiet.setEnabled(true);
                btnThemHD.setEnabled(true);
                btnThemHD1.setEnabled(true);
            } else {
                txtSoThangTT.setEnabled(false);
                txtTienKhachDua.setEnabled(false);
                txtNgayThanhToan.setEnabled(false);
                btnXemChiTiet.setEnabled(false);
                btnThemHD.setEnabled(false);
                btnThemHD1.setEnabled(false);
                this.row = -1;
            }
            this.fillTable();
            clearForm();
        }
    }

    private void viewDichVuCT() {
        CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
        cardLayout.next(jPanel1);
    }

    private boolean isInvalidSoTTT() {
        String soThangTT = txtSoThangTT.getText();
        String soThangCanTT = lblSoThangCanTT.getText();
        if (!soThangTT.isEmpty()) {
            try {
                Integer.parseInt(soThangTT);
                return true;
            } catch (Exception e) {
                DialogHelper.alert(this, "Bạn cần nhập số cho ô số tháng thanh toán");
                txtSoThangTT.setText("");
                return false;
            }
        } else {
            return false;
        }
    }

    public void exportpdf() {
        try {
            txtbill.getText();
            txtbill.print();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi lưu file");
        }

    }

    private void setFormDVCT() {

        HoaDon hd = this.getForm();
        BenhNhan bn = benhNhanDAO.selectByID(hd.getMaBN());
        Phong phong = phongDAO.findById(bn.getMaPhong());
        DichVuCT listDV = dvctDAO.selectByHD(bn.getMaBN(), hd.getNgayBDTT(), hd.getNgayKTTT());
//        DichVu dv = dichVuDAO.selectByID(listDV.getMaDV());

        lblTenBN.setText(bn.getHoTen());
        lblMaPhong2.setText(bn.getMaPhong());
        lblGiaPhong.setText(FormatHepler.formatMoney(phong.getGia() * hd.getThoiGian()));
        lblSoThangTT.setText(String.valueOf(hd.getThoiGian()));
        lblNgayBatDau2.setText(DateHelper.toString(hd.getNgayBDTT()));
        lblNgayKetThuc2.setText(DateHelper.toString(hd.getNgayKTTT()));
        lblTongTien2.setText(FormatHepler.formatMoney(hd.getTongTien()));
        if (lblTienThua.getText().equals("") && txtTienKhachDua.getText().equals("")) {
            billsaukhithanhtoan();
        } else {
            bill();
        }
    }

    private void fillTableDVCT() {
        HoaDon hd = this.getForm();
        BenhNhan bn = benhNhanDAO.selectByID(hd.getMaBN());
        DefaultTableModel model = (DefaultTableModel) tblDichVuCT.getModel();
        model.setRowCount(0);
        try {
            List<DichVuCT> listDV = dvctDAO.selectByMaBNAndNgayDK(bn.getMaBN(), hd.getNgayBDTT(), hd.getNgayKTTT());
            for (DichVuCT dichVuCT : listDV) {
                DichVu dv = dichVuDAO.selectByID(dichVuCT.getMaDV());
                Object[] row = {
                    dv.getMaDV(),
                    dv.getTenDV(),
                    DateHelper.toString(dichVuCT.getNgayDK()),
                    FormatHepler.formatMoney(dv.getGia())
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
            System.out.println(e);
        }
    }

    private void showMenuRedo() {
        jPopupMenu1.show(lblMenuRedo, -40, 30);
    }

    private void undo() {
        HoaDon hd = listUndo.get(index);
        if (listBrowser.get(index) == 1) {
            hoaDonDAO.delete(hd.getMaHD());
        } else if (listBrowser.get(index) == 2) {
            hoaDonDAO.update(hd);
        } else if (listBrowser.get(index) == 3) {
            hoaDonDAO.insert(hd);
        }
        fillTable();
    }

    private void fillTienThua() {
        if (!txtTienKhachDua.getText().isEmpty()) {
            if (CheckHelper.checkGia(txtTienKhachDua)) {
                if (!lblTongTien.getText().isEmpty()) {
                    double tienKhachDua = FormatHepler.formatMoneyToDouble(txtTienKhachDua.getText());
                    double tongTien = FormatHepler.formatMoneyToDouble(lblTongTien.getText());
                    if (tienKhachDua >= tongTien) {
                        lblTienThua.setText(FormatHepler.formatMoney(tienKhachDua - tongTien));
                    }else{
                        lblTienThua.setText("");
                    }
                } else {
                    DialogHelper.alert(this, "Bạn cần nhập số tháng muốn được thanh toán trước");
                    txtTienKhachDua.setText("");
                    txtSoThangTT.requestFocus();
                }
            }
        }
    }
}
