/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DuAnDAO.*;
import Entity.*;
import Helper.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class HoatDongJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HoatDongJPanel
     */
    public HoatDongJPanel() {
        initComponents();

        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel65 = new javax.swing.JLabel();
        pnlHoatDong = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel67 = new javax.swing.JLabel();
        txtTenHD = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnNew = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoatDong = new rojeru_san.complementos.RSTableMetro();
        pnlHoatDong1 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        btnNew1 = new javax.swing.JButton();
        btnInsert1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        txtNgayThucHien = new com.toedter.calendar.JDateChooser();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtGhiChu2 = new javax.swing.JTextArea();
        cboTenBN = new javax.swing.JComboBox<String>();
        cboTenHoatDong = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTHoatDong = new rojeru_san.complementos.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 875));

        jLabel65.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(50, 133, 253));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("QUẢN LÝ HOẠT ĐỘNG");

        pnlHoatDong.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoatDong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel67.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(102, 102, 102));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tenHoatDong.png"))); // NOI18N
        jLabel67.setText("Tên hoạt động");

        txtTenHD.setBackground(new java.awt.Color(240, 240, 240));
        txtTenHD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTenHD.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));

        jLabel70.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(102, 102, 102));
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/moTa.png"))); // NOI18N
        jLabel70.setText("Mô tả");

        txtGhiChu.setBackground(new java.awt.Color(240, 240, 240));
        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtGhiChu.setRows(5);
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        jScrollPane15.setViewportView(txtGhiChu);

        btnNew.setBackground(new java.awt.Color(50, 133, 253));
        btnNew.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("MỚI");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNew.setContentAreaFilled(false);
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(50, 133, 253));
        btnInsert.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setText("THÊM");
        btnInsert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInsert.setContentAreaFilled(false);
        btnInsert.setOpaque(true);
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertMouseExited(evt);
            }
        });
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(50, 133, 253));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("CẬP NHẬT");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setOpaque(true);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(50, 133, 253));
        btnDelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("XÓA");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(50, 133, 253));
        btnFirst.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/start.png"))); // NOI18N
        btnFirst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFirst.setContentAreaFilled(false);
        btnFirst.setOpaque(true);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(50, 133, 253));
        btnPrev.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/back.png"))); // NOI18N
        btnPrev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPrev.setContentAreaFilled(false);
        btnPrev.setOpaque(true);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(50, 133, 253));
        btnNext.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/next.png"))); // NOI18N
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNext.setContentAreaFilled(false);
        btnNext.setOpaque(true);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(50, 133, 253));
        btnLast.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/end.png"))); // NOI18N
        btnLast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLast.setContentAreaFilled(false);
        btnLast.setOpaque(true);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/timKiem.png"))); // NOI18N

        txtTimKiem.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(50, 133, 253)));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        tblHoatDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hoạt động", "Tên hoạt động", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoatDong.setColorBackgoundHead(new java.awt.Color(51, 133, 253));
        tblHoatDong.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblHoatDong.setColorBordeHead(new java.awt.Color(51, 133, 253));
        tblHoatDong.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblHoatDong.setColorFilasForeground1(new java.awt.Color(51, 133, 253));
        tblHoatDong.setColorFilasForeground2(new java.awt.Color(51, 133, 253));
        tblHoatDong.setColorSelBackgound(new java.awt.Color(51, 133, 253));
        tblHoatDong.setFuenteFilas(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblHoatDong.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblHoatDong.setFuenteHead(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tblHoatDong.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblHoatDong.setRowHeight(25);
        tblHoatDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoatDongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoatDong);

        javax.swing.GroupLayout pnlHoatDongLayout = new javax.swing.GroupLayout(pnlHoatDong);
        pnlHoatDong.setLayout(pnlHoatDongLayout);
        pnlHoatDongLayout.setHorizontalGroup(
            pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoatDongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHoatDongLayout.createSequentialGroup()
                        .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHoatDongLayout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlHoatDongLayout.createSequentialGroup()
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoatDongLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel68)
                        .addGap(0, 0, 0)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHoatDongLayout.createSequentialGroup()
                        .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(jLabel67))
                        .addGap(27, 27, 27)
                        .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenHD)
                            .addComponent(jScrollPane15))))
                .addContainerGap())
            .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHoatDongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHoatDongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlHoatDongLayout.setVerticalGroup(
            pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoatDongLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67))
                .addGap(25, 25, 25)
                .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(350, 350, 350)
                .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHoatDongLayout.createSequentialGroup()
                    .addGap(546, 546, 546)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
            .addGroup(pnlHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHoatDongLayout.createSequentialGroup()
                    .addGap(248, 248, 248)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        pnlHoatDong1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoatDong1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel69.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(102, 102, 102));
        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tenBN.png"))); // NOI18N
        jLabel69.setText("Tên bệnh nhân");

        jLabel71.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(102, 102, 102));
        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/tenHoatDong.png"))); // NOI18N
        jLabel71.setText("Tên hoạt động");

        btnNew1.setBackground(new java.awt.Color(50, 133, 253));
        btnNew1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNew1.setForeground(new java.awt.Color(255, 255, 255));
        btnNew1.setText("MỚI");
        btnNew1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNew1.setContentAreaFilled(false);
        btnNew1.setOpaque(true);
        btnNew1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNew1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNew1MouseExited(evt);
            }
        });
        btnNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew1ActionPerformed(evt);
            }
        });

        btnInsert1.setBackground(new java.awt.Color(50, 133, 253));
        btnInsert1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnInsert1.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert1.setText("THÊM");
        btnInsert1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInsert1.setContentAreaFilled(false);
        btnInsert1.setOpaque(true);
        btnInsert1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsert1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsert1MouseExited(evt);
            }
        });
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(50, 133, 253));
        btnDelete1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("XÓA");
        btnDelete1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelete1.setContentAreaFilled(false);
        btnDelete1.setOpaque(true);
        btnDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete1MouseExited(evt);
            }
        });
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(102, 102, 102));
        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/ngayThucHien.png"))); // NOI18N
        jLabel73.setText("Ngày thực hiện");

        txtNgayThucHien.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        txtNgayThucHien.setDateFormatString("dd/MM/yyyy");
        txtNgayThucHien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel74.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(102, 102, 102));
        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Icon/ghiChu.png"))); // NOI18N
        jLabel74.setText("Ghi chú");

        txtGhiChu2.setBackground(new java.awt.Color(240, 240, 240));
        txtGhiChu2.setColumns(20);
        txtGhiChu2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtGhiChu2.setRows(5);
        txtGhiChu2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        jScrollPane18.setViewportView(txtGhiChu2);

        cboTenBN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboTenBN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        cboTenBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenBNActionPerformed(evt);
            }
        });

        cboTenHoatDong.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboTenHoatDong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 133, 253)));
        cboTenHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenHoatDongActionPerformed(evt);
            }
        });

        tblCTHoatDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hoạt động chi tiết", "Mã hoạt động", "Tên hoạt động", "Ngày thực hiện", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTHoatDong.setColorBackgoundHead(new java.awt.Color(51, 133, 253));
        tblCTHoatDong.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblCTHoatDong.setColorBordeHead(new java.awt.Color(51, 133, 253));
        tblCTHoatDong.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblCTHoatDong.setColorFilasForeground1(new java.awt.Color(51, 133, 253));
        tblCTHoatDong.setColorFilasForeground2(new java.awt.Color(51, 133, 253));
        tblCTHoatDong.setColorSelBackgound(new java.awt.Color(51, 133, 253));
        tblCTHoatDong.setFuenteFilas(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblCTHoatDong.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblCTHoatDong.setFuenteHead(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tblCTHoatDong.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblCTHoatDong.setRowHeight(25);
        tblCTHoatDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHoatDongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTHoatDong);

        javax.swing.GroupLayout pnlHoatDong1Layout = new javax.swing.GroupLayout(pnlHoatDong1);
        pnlHoatDong1.setLayout(pnlHoatDong1Layout);
        pnlHoatDong1Layout.setHorizontalGroup(
            pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                        .addComponent(btnNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator11)
                    .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                        .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel71)
                            .addComponent(jLabel73)
                            .addComponent(jLabel74)
                            .addComponent(jLabel69))
                        .addGap(27, 27, 27)
                        .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                            .addComponent(txtNgayThucHien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTenBN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTenHoatDong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlHoatDong1Layout.setVerticalGroup(
            pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoatDong1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(cboTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(cboTenHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayThucHien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(330, 330, 330))
                    .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)))
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(pnlHoatDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlHoatDong1Layout.createSequentialGroup()
                    .addGap(368, 368, 368)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlHoatDong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel65)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHoatDong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHoatDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clear();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insert();
        this.isLoad = false;
        fillComboxHoatDong();
        this.isLoad = true;
        this.fillTableHDCT();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
        this.isLoad = false;
        fillComboxHoatDong();
        this.isLoad = true;
        this.fillTableHDCT();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
        this.isLoad = false;
        fillComboxHoatDong();
        this.isLoad = true;
        this.fillTableHDCT();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        this.index--;
        this.edit();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.index++;
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.index = tblHoatDong.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        this.load();
        this.clear();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew1ActionPerformed
        this.clearFormHDCT();
    }//GEN-LAST:event_btnNew1ActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
        this.insertHDCT();
    }//GEN-LAST:event_btnInsert1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        this.deleteHDCT();
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void cboTenBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenBNActionPerformed
        selectCbo();
    }//GEN-LAST:event_cboTenBNActionPerformed

    private void cboTenHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenHoatDongActionPerformed
        selectCbo();
    }//GEN-LAST:event_cboTenHoatDongActionPerformed

    private void tblHoatDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoatDongMouseClicked
        if (evt.getClickCount() == 2) {
            this.index = tblHoatDong.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();
            }
        }
    }//GEN-LAST:event_tblHoatDongMouseClicked

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnInsertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseEntered
        btnInsert.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnInsertMouseEntered

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        btnUpdate.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnNewMouseExited

    private void btnInsertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseExited
        btnInsert.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnInsertMouseExited

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void tblCTHoatDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoatDongMouseClicked
        if (evt.getClickCount() == 2) {
            isLoad = false;
            this.rowHDCT = tblCTHoatDong.getSelectedRow();
            this.editHDCT();
        }
    }//GEN-LAST:event_tblCTHoatDongMouseClicked

    private void btnNew1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNew1MouseEntered
        btnNew1.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnNew1MouseEntered

    private void btnInsert1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsert1MouseEntered
        btnInsert1.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnInsert1MouseEntered

    private void btnDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseEntered
        btnDelete1.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnDelete1MouseEntered

    private void btnNew1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNew1MouseExited
        btnNew1.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnNew1MouseExited

    private void btnInsert1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsert1MouseExited
        btnInsert1.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnInsert1MouseExited

    private void btnDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseExited
        btnDelete1.setBackground(new Color(51, 133, 253));
    }//GEN-LAST:event_btnDelete1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNew1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboTenBN;
    private javax.swing.JComboBox<String> cboTenHoatDong;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JPanel pnlHoatDong;
    private javax.swing.JPanel pnlHoatDong1;
    private rojeru_san.complementos.RSTableMetro tblCTHoatDong;
    private rojeru_san.complementos.RSTableMetro tblHoatDong;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextArea txtGhiChu2;
    private com.toedter.calendar.JDateChooser txtNgayThucHien;
    private javax.swing.JTextField txtTenHD;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    boolean isLoad = false;
    int rowHDCT = -1;
    int index = 0;
    HoatDongDAO dao = new HoatDongDAO();
    HoatDongCTDAO hdctdao = new HoatDongCTDAO();
    BenhNhanDAO bndao = new BenhNhanDAO();

    private void init() {
        this.load();
        this.setStatus(true);
        if (ShareHelper.isLogin1()) {
            btnInsert.setVisible(false);
            btnUpdate.setVisible(false);
            btnDelete.setVisible(false);
            btnNew.setVisible(false);
        } else {
            btnInsert.setVisible(true);
            btnUpdate.setVisible(true);
            btnDelete.setVisible(true);
        }

        this.fillComboxBenhNhan();
        this.fillComboxHoatDong();
        this.fillTableHDCT();
        //      this.rowHDCT ;
        this.updateStatusHDCT();
        txtNgayThucHien.setDate(new Date());
    }

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblHoatDong.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiem.getText();
            List<HoatDong> list = dao.selectByKeyword(keyword);
            //List<HoatDong> list = dao.select();
            for (HoatDong cd : list) {
                Object[] row = {
                    cd.getMaHoatDong(),
                    cd.getTenHoatDong(),
                    cd.getGhichu()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void setModel(HoatDong model) {
        txtTenHD.setText(model.getTenHoatDong());
        txtGhiChu.setText(model.getGhichu());

    }

    HoatDong getModel() {
        HoatDong model = new HoatDong();
        model.setTenHoatDong(txtTenHD.getText());
        model.setGhichu(txtGhiChu.getText());
        return model;
    }

    void insert() {
        HoatDong model = getModel();
        if (validateData()) {
            try {
                dao.insert(model);
                this.load();
                this.clear();
                DialogHelper.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Thêm mới thất bại!");
            }
        }
    }

    void clear() {
        this.setModel(new HoatDong());
        this.setStatus(true);
    }

    void setStatus(boolean insertable) {

        btnInsert.setEnabled(insertable);
        btnUpdate.setEnabled(!insertable);
        btnDelete.setEnabled(!insertable);
        boolean first = this.index > 0;
        boolean last = this.index < tblHoatDong.getRowCount() - 1;
        btnFirst.setEnabled(!insertable && first);
        btnPrev.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    }

    void edit() {
        try {
            int maHD = (int) tblHoatDong.getValueAt(this.index, 0);
            HoatDong model = dao.findById(maHD);
            if (model != null) {
                this.setModel(model);
                this.setStatus(false);
                tblHoatDong.setRowSelectionInterval(index, index);
            }
            this.clearFormHDCT();
            cboTenHoatDong.getModel().setSelectedItem(model);
            this.fillTableHDCT();
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void update() {
        if (validateData()) {
            int maHD = (int) tblHoatDong.getValueAt(index, 0);
            HoatDong model = getModel();
            model.setMaHoatDong(maHD);
            try {
                dao.update(model);
                this.load();
                this.clear();
                DialogHelper.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Cập nhật thất bại!");
                e.printStackTrace();
            }
        }
    }

    void delete() {
        if (ShareHelper.isManager()) {
            DialogHelper.alert(this, "Bạn không có quyền xóa");
        } else {
            if (DialogHelper.confirm(this, "Bạn có muốn xóa hay không?")) {
                int maHD = (int) tblHoatDong.getValueAt(this.index, 0);
                try {
                    dao.delete(maHD);
                    this.load();
                    clear();
                    DialogHelper.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    DialogHelper.alert(this, "Xóa thất bại!");
                }

            }

        }
    }

    void timKiem() {
        this.load();
        this.clear();
        this.index = -1;
    }

    private boolean validateData() {
        if (txtTenHD.getText().isEmpty()) {
            DialogHelper.alert(this, "Tên hoạt động không được để trống");
            txtTenHD.requestFocus();
            return false;
        } else if (txtGhiChu.getText().isEmpty()) {
            DialogHelper.alert(this, "Giá không được để trống");
            txtGhiChu.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    void clearFormHDCT() {
        cboTenBN.setSelectedIndex(0);
        cboTenHoatDong.setSelectedIndex(0);
        txtNgayThucHien.setDate(new Date());
        txtGhiChu2.setText("");
        load();
        this.rowHDCT = -1;
        this.updateStatusHDCT();
    }

    void insertHDCT() {
        if (validateDataHDCT()) {
            HoatDongCT HDCT = getFormHDCT();
            try {
                hdctdao.insert(HDCT);
                this.fillTableHDCT();
                this.clearFormHDCT();
                DialogHelper.alert(this, "Thêm mới thành công");
            } catch (Exception e) {
                DialogHelper.alert(this, "Thêm mới thất bại");
            }
        }
    }

    void deleteHDCT() {
        if (ShareHelper.isManager()) {
            DialogHelper.alert(this, "Bạn không có quyền xóa");
        } else {
            int maHDCT = (Integer) tblCTHoatDong.getValueAt(rowHDCT, 0);
            if (DialogHelper.confirm(this, "Bạn có muốn xóa không")) {
                try {
                    hdctdao.delete(maHDCT);
                    this.fillTableHDCT();
                    this.clearFormHDCT();
                    DialogHelper.alert(this, "Đã xóa thành công");
                } catch (Exception e) {
                    DialogHelper.alert(this, "Xóa thất bại");
                    System.out.println(e);
                }
            }

        }
    }

    void setFormHDCT(HoatDongCT HDCT) {
        HoatDong hd = dao.findById(HDCT.getMaHD());
        BenhNhan bn = bndao.selectByID(HDCT.getMaBN());
        cboTenHoatDong.getModel().setSelectedItem(hd);
        cboTenBN.getModel().setSelectedItem(bn);
        txtNgayThucHien.setDate(HDCT.getNgayThucHien());
        txtGhiChu2.setText(HDCT.getGhiChu());
    }

    HoatDongCT getFormHDCT() {
        HoatDongCT HDCT = new HoatDongCT();
        HoatDong hd = (HoatDong) cboTenHoatDong.getSelectedItem();
        BenhNhan bn = (BenhNhan) cboTenBN.getSelectedItem();
        HDCT.setMaHD(hd.getMaHoatDong());
        HDCT.setMaBN(bn.getMaBN());
        HDCT.setNgayThucHien(txtNgayThucHien.getDate());
        HDCT.setGhiChu(txtGhiChu2.getText());
        return HDCT;
    }

    void fillTableHDCT() {
        DefaultTableModel model = (DefaultTableModel) tblCTHoatDong.getModel();
        model.setRowCount(0);

        BenhNhan bn = (BenhNhan) cboTenBN.getSelectedItem();
        HoatDong hd = (HoatDong) cboTenHoatDong.getSelectedItem();

        List<HoatDongCT> list = new ArrayList<>();
        if (bn.getMaBN() == -1 && hd.getMaHoatDong() == -1) {
            list.clear();
            list = hdctdao.selectAll();
        } else if (bn.getMaBN() == -1) {
            list.clear();
            list = hdctdao.selectByMaHD(hd.getMaHoatDong());
        } else if (hd.getMaHoatDong() == -1) {
            list.clear();
            list = hdctdao.selectByMaBN(bn.getMaBN());
        } else {
            list.clear();
            list = hdctdao.selectByMaBNAndHD(bn.getMaBN(), hd.getMaHoatDong());
        }
        if (ShareHelper.isLogin()) {
            try {
                for (HoatDongCT HDCT : list) {
                    if (HDCT.getMaBN() >= 1) {
                        Object[] rowHDCT = {
                            HDCT.getMaHDCT(),
                            dao.findById(HDCT.getMaHD()),
                            bndao.selectByID(HDCT.getMaBN()),
                            DateHelper.toString(HDCT.getNgayThucHien()),
                            HDCT.getGhiChu()
                        };
                        model.addRow(rowHDCT);
                    }
                }
                isLoad = true;
            } catch (Exception e) {
                DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
                System.out.println(e);
            }
        } else {
            List<HoatDongCT> list1 = hdctdao.selectByMaBN1(ShareHelper.nguoidung.getMabn());
            try {
                for (HoatDongCT HDCT : list1) {
                    Object[] rowHDCT = {
                        HDCT.getMaHDCT(),
                        dao.findById(HDCT.getMaHD()),
                        bndao.selectByID(ShareHelper.nguoidung.getMabn()),
                        DateHelper.toString(HDCT.getNgayThucHien()),
                        HDCT.getGhiChu()
                    };
                    model.addRow(rowHDCT);
                }
                isLoad = true;
            } catch (Exception e) {
                DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
                System.out.println(e);
            }
        }

    }

    void editHDCT() {
        int maHDCT = (Integer) tblCTHoatDong.getValueAt(this.rowHDCT, 0);
        HoatDongCT HDCT = hdctdao.selectByID(maHDCT);
        this.setFormHDCT(HDCT);
        this.updateStatusHDCT();
        isLoad = true;
    }

    void updateStatusHDCT() {
        boolean edit = (this.rowHDCT >= 0);
        boolean frist = (this.rowHDCT == 0);
        boolean last = (this.rowHDCT == tblCTHoatDong.getRowCount() - 1);
        btnInsert1.setEnabled(!edit);
        btnDelete1.setEnabled(edit);
    }

    boolean validateDataHDCT() {
        BenhNhan bn = (BenhNhan) cboTenBN.getSelectedItem();
        HoatDong hd = (HoatDong) cboTenHoatDong.getSelectedItem();

        if (hd.getMaHoatDong() == -1) {
            DialogHelper.alert(this, "Bạn chưa chọn hoạt động");
            return false;
        } else if (bn.getMaBN() == -1) {
            DialogHelper.alert(this, "Bạn chưa chọn bệnh nhân");
            return false;
        } else {
            return true;
        }
    }

    void fillComboxHoatDong() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenHoatDong.getModel();
        model.removeAllElements();
        HoatDong hoatDong = new HoatDong();
        hoatDong.setTenHoatDong("Tất cả");
        hoatDong.setMaHoatDong(-1);
        model.addElement(hoatDong);
        List<HoatDong> list = dao.select();
        for (HoatDong hd : list) {
            model.addElement(hd);
        }
    }

    void fillComboxBenhNhan() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenBN.getModel();
        model.removeAllElements();
        BenhNhan benhNhan = new BenhNhan();
        benhNhan.setHoTen("Tất cả");
        benhNhan.setMaBN(-1);
        model.addElement(benhNhan);
        if (ShareHelper.isLogin()) {
            List<BenhNhan> list = bndao.selectAll();
            for (BenhNhan bn : list) {
                model.addElement(bn);
            }
        } else {
            List<BenhNhan> list = bndao.findlistById(ShareHelper.nguoidung.getMabn());
            for (BenhNhan bn : list) {
                model.addElement(bn);
            }
        }

    }

    void selectCbo() {
        if (isLoad) {
            this.fillTableHDCT();
        }
    }

}
